name: My First Workflow

on: push

jobs:
    fisrt_job:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repo
              uses: actions/checkout@v5

            - name: Welcome message # Optional
              run: echo "My first Github Actions Job"

            - name: List files
              run: ls -al

            - name: Show Current Dir
              run: pwd

            - name: Read file
              run: cat README.md