name: My First Workflow

on: push

jobs:
    fisrt_job:
        runs-on: ubuntu-latest
        steps:
            - name: Welcome message # Optional
              run: echo "My first Github Actions Job"

            - name: List files
              run: ls

            - name: Read file
              run: cat README.md